### PR TITLE
fix: restore InferStructuralSharing and handleHashScroll in published .d.ts files

### LINKED ISSUE #5116: InferStructuralSharing missing in published types (esm/cjs)
### Which project does this relate to?

Router

### Describe the bug

After updating from @tanstack/router 1.129.8 to 1.131.36 I got typescript compilation errors  for the distributed types:

```
node_modules/@tanstack/react-router/dist/esm/index.d.ts:49:36 - error TS2305: Module '"./typePrimitives.js"' has no exported member 'InferStructuralSharing'.

49 export type { ValidateLinkOptions, InferStructuralSharing, ValidateUseSearchOptions, ValidateUseParamsOptions, ValidateLinkOptionsArray, } from './typePrimitives.js';
                                      ~~~~~~~~~~~~~~~~~~~~~~
```

When reviewing the node_modules/@tanstack/react-router/dist/esm/typePrimitives.d.ts file, it lacks the InferStructuralSharing type.

Version 1.129.8 includes this type, defined in typePrimitives.d.ts as 

```
/**
 * @internal
 */
export type InferStructuralSharing<TOptions> = TOptions extends {
    structuralSharing: infer TStructuralSharing;
} ? TStructuralSharing : unknown;

```

### Your Example Website or App

https://stackblitz.com/edit/github-h1spuhyh?file=tsconfig.json

### Steps to Reproduce the Bug or Issue

set skipLibCheck: false

```
npm i
node_modules/typescript/bin/tsc --noEmit
```

### Expected behavior

No  typescript errors

### Screenshots or Videos

Image

### Platform

- Router Version: 1.131.36
- Typescript: any recent version

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vedant416**
Fixes #5116

### Root Cause
In PR #4907, the TypeScript compiler option `stripInternal` was enabled in tsconfig.json, which causes TypeScript to remove any declarations marked with `@internal` from the published `.d.ts` files.

This resulted in TypeScript compilation errors for library users who have set the TypeScript compiler option `skipLibCheck` to `false`, because the following members were missing:

- `InferStructuralSharing` type in `react-router`
- `handleHashScroll` function in `router-core > scrollRestoration`

### Fix
- This PR replaces the `@internal` annotation with the `@private` annotation.

## Summary by CodeRabbit

* **Documentation**
  * Updated internal API annotations in routing packages to mark certain items as private, improving the accuracy of generated developer documentation.
  * No changes to public APIs, behavior, or performance.
  * No user-facing impact.

### CODE REVIEW

**Comment by Sheraff** [comment]
@vedant416 out of curiosity, what is your use-case for `skipLibCheck: false`?

**Comment by vedant416** [comment]
> @vedant416 out of curiosity, what is your use-case for `skipLibCheck: false`?

@Sheraff the original reporter of issue #5116, @perbergland, might be able to share more about their use case.
For reference, the `skipLibCheck: false` is default compiler option (see [TS docs](https://www.typescriptlang.org/docs/handbook/compiler-options.html#:~:text=%2D%2DskipLibCheck,false)), so I think it was a good catch by @perbergland.
