### ISSUE TITLE
Context type inference on createRouter is not working anymore

### ISSUE THREAD

**Issue by zenoxs** [TanStack/router#1943]
### Describe the bug

When creating a new router with createRouter and a context value, the returned router doesn't contain valid typing on the options.context properties. This was working in version 1.34.5 but doesn't work anymore in version 1.44.2 (I did not test versions in between).

### Your Example Website or App

https://stackblitz.com/edit/github-dysjpq?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

```tsx
import ReactDOM from 'react-dom/client';
import { RouterProvider, createRouter } from '@tanstack/react-router';
import { routeTree } from './routeTree.gen';

// Set up a Router instance
const router = createRouter({
  routeTree,
  defaultPreload: 'intent',
  context: {
    value: 'test',
  },
});

// Type inference is not working there (Property 'value' does not exist on type 'AnyContext'.)
const value = router.options.context.value;
```

### Expected behavior

Type inference on `router.options.context.value` should be inferred correctly.

### Platform

- OS: Windows
- Browser: Chrome

**Comment by archer3cl** [comment]
It is failing again on ^1.49.2.
Using the same stackblitz from OP.
When loading main.tsx for the first time inference seems to work but if you delete and retype the value inference fails.
