### ISSUE TITLE
Tanstack Start nor working with Clerk 0.23+

### ISSUE THREAD

**Issue by jt-helsinki** [TanStack/router#5093]
### Which project does this relate to?

Start

### Describe the bug

Trying to setup Clerk as per examples and documentation. Using the latest version of `@clerk/tanstack-react-start` (^0.23.4).

Error:

> TypeError: (0 , __vite_ssr_import_1__.default) is not a function
> at eval (/~start/server-entry.tsx:7:10)
> at eval (/workspace/router/examples/react/start-clerk-basic/node_modules/@tanstack/start-server-core/src/h3.ts:223:38)
> at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14)
> at runWithEvent (/workspace/router/examples/react/start-clerk-basic/node_modules/@tanstack/start-server-core/src/h3.ts:237:23)
> at Module.eval (/workspace/router/examples/react/start-clerk-basic/node_modules/@tanstack/start-server-core/src/h3.ts:223:12)
> at file:///workspace/router/examples/react/start-clerk-basic/node_modules/@tanstack/start-plugin-core/dist/esm/dev-server-plugin/plugin.js:47:58
> /workspace/router/examples/react/start-clerk-basic/node_modules/@tanstack/start-server-core/src/h3.ts:243
> throw new Error(
> ^
> 
> 
> Error: No HTTPEvent found in AsyncLocalStorage. Make sure you are using the function within the server runtime.
> at getEvent (/workspace/router/examples/react/start-clerk-basic/node_modules/@tanstack/start-server-core/src/h3.ts:243:11)
> at eval (/workspace/router/examples/react/start-clerk-basic/node_modules/@tanstack/start-server-core/src/h3.ts:287:20)
> at eval (/workspace/router/examples/react/start-clerk-basic/node_modules/@clerk/tanstack-react-start/src/server/middlewareHandler.ts:24:21)
> at eval (/workspace/router/examples/react/start-clerk-basic/src/server.ts:14:16)
> at async ESModulesEvaluator.runInlinedModule (file:///workspace/router/examples/react/start-clerk-basic/node_modules/vite/dist/node/module-runner.js:1062:5)
> at async ModuleRunner.directRequest (file:///workspace/router/examples/react/start-clerk-basic/node_modules/vite/dist/node/module-runner.js:1284:61)
> at async ModuleRunner.cachedRequest (file:///workspace/router/examples/react/start-clerk-basic/node_modules/vite/dist/node/module-runner.js:1180:76)
> at async eval (/~start/server-entry.tsx:3:1)
> at async ESModulesEvaluator.runInlinedModule (file:///workspace/router/examples/react/start-clerk-basic/node_modules/vite/dist/node/module-runner.js:1062:5)
> at async ModuleRunner.directRequest (file:///workspace/router/examples/react/start-clerk-basic/node_modules/vite/dist/node/module-runner.js:1284:61)
> 
> Node.js v23.10.0

### Your Example Website or App

https://github.com/TanStack/router/tree/main/examples/react/start-clerk-basic

### Steps to Reproduce the Bug or Issue

1. Use the example found here: https://github.com/TanStack/router/tree/main/examples/react/start-clerk-basic
2. Update the @clerk/tanstack-react-start version to 0.23 +
3. Start the application
4. visit https://localhost:3000

### Expected behavior

No errors. 

### Platform

- Router / Start Version: ^1.131.35
- OS: macOs
- Browser: any
- Browser Version: n/a
- Bundler: Vite
- Bundler Version: ^6.3.5 (error experienced on later versions too)

### Additional context

This works without a problem on `@clerk/tanstack-react-start` version 0.22.x and below. Any 0.23.x version causes the error. 

`@clerk/tanstack-react-start` package changelog here:

https://github.com/clerk/javascript/blob/main/packages/tanstack-react-start/CHANGELOG.md

**Comment by jt-helsinki** [comment]
The examples/docs need updating:

server.ts

```
import {
    createStartHandler,
    defaultStreamHandler,
    defineHandlerCallback,
} from '@tanstack/react-start/server';
import { createRouter } from './router';
import { createClerkHandler } from '@clerk/tanstack-react-start/server';

const handlerFactory = createClerkHandler(
    createStartHandler({
        createRouter,
    }),
);

export default defineHandlerCallback(async (event) => {
    const startHandler = await handlerFactory(defaultStreamHandler)
    return startHandler(event)
});
```

reference: https://clerk.com/docs/quickstarts/tanstack-react-start
